version: '2'

includes:
  console: ./taskfiles/console.yml

vars:
  SERVICE: "web"
  SERVICE_ARGS: ""

  GO_PACKAGES:
    sh: go list ./...

tasks:

  build:
    desc: build sde
    cmds:
      - go build cmd/...
      - go build main.go

  test:
    desc: test sde 
    cmds:
      - task test:unit
      - task test:functional
      - task test:system

  utils:
    desc: download and install utilities
    cmds:
      - go get -u golang.org/x/lint/golint
      - go get -u github.com/spf13/cobra

  lint:
    desc: run golint on go packages
    cmds:
      - golint {{catLines .GO_PACKAGES}}

  test:unit:
    desc: unit test 
    cmds: 
      - task: console:print
        vars: { message: "unit test not implemented yet" }

  test:functional:
    desc: functional test 
    cmds: 
      - task: console:print
        vars: { message: "functional test not implemented yet" }

  test:system:
    desc: system test
    cmds: 
      - task: console:print
        vars: { message: "system test not implemented yet" }

  run:web:service:
    desc: run sde service --name web
    cmds:
      - go run main.go service --name web {{.SERVICE_ARGS}}

  run:workspace:service:
    desc: run sde service --name workspace
    cmds:
      - go run main.go service --name workspace {{.SERVICE_ARGS}}
