version: '2'

includes:
  console: ./taskfiles/console.yml

vars:
  SERVICE: "web"
  SERVICE_ARGS: ""

  GO_PACKAGES:
    sh: go list ./...

tasks:

  build:
    desc: go build main.go
    cmds:
      - go build cmd/...
      - go build main.go

  test:
    desc: run unit, functional and system test 
    cmds:
      - task test:unit
      - task test:functional
      - task test:system

  utils:
    desc: download and install go utilities
    cmds:
      - go get -u golang.org/x/lint/golint
      - go get -u github.com/spf13/cobra

  lint:
    desc: golint $(go list ./...)
    cmds:
      - golint {{catLines .GO_PACKAGES}}

  test:unit:
    desc: unit test 
    cmds: 
      - task: console:print
        vars: { message: "unit test not implemented yet" }

  test:functional:
    desc: functional test 
    cmds: 
      - task: console:print
        vars: { message: "functional test not implemented yet" }

  test:system:
    desc: system test
    cmds: 
      - task: console:print
        vars: { message: "system test not implemented yet" }

  run:svc:web:
    desc: go run main.go service --name web
    cmds:
      - go run main.go service --name web {{.SERVICE_ARGS}}

  run:svc:workspace:
    desc: go run main.go service --name workspace
    cmds:
      - go run main.go service --name workspace {{.SERVICE_ARGS}}
