version: '3'

vars:
  BROWSER     : Brave Browser
  GO_PACKAGES :
    sh: go list ./...
  SDE_IPADDR  : 192.168.33.10

tasks:
  cuelang:
    desc: run cue service
    cmds:
      - go run main.go cue

  cuelang:browser:
    desc: launch browser
    cmds:
      - open -a "{{.BROWSER}}" "http://127.0.0.1:3001"

  cuelang:validate:
    desc: run cue validate
    cmds:
      - go run main.go cue validate

  cuelang:service:
    desc: run cue service
    cmds:
      - go run main.go cue service

  golang:build:
    desc: build workspace
    cmds:
      - go build ./...

  golang:lint:
    desc: run golint
    cmds:
      - golint {{catLines .GO_PACKAGES}}

  golang:test:
    desc: run go test
    cmds:
      - go test ./...

  golang:utils:
    desc: download and install utilities
    cmds:
      - go get -u golang.org/x/lint/golint
      - go get -u github.com/spf13/cobra

  sde:bazel:examples:
    desc: clone bazel examples
    dir: '/opt/sde/vagrant/sde'
    cmds:
      - mkdir -p bazel
      - cd bazel && git clone https://github.com/bazelbuild/examples

  sde:vagrant:halt:
    desc: halt sde guest vm
    dir: '/opt/sde/vagrant/sde'
    cmds:
      - vagrant halt

  sde:vagrant:init:
    desc: populate sde vagrantfile
    cmds:
      - cp internal/onboarding/sde/Vagrantfile /opt/sde/vagrant/sde

  sde:vagrant:ping:
    desc: ping sde guest vm
    cmds:
      - ping -c 2 {{.SDE_IPADDR}}

  sde:vagrant:provision:
    desc: bring up sde guest vm
    dir: '/opt/sde/vagrant/sde'
    deps: [sde:vagrant:init]
    cmds:
      - SDE_IPADDR="{{.SDE_IPADDR}}" vagrant up --provision

  sde:vagrant:ssh:
    desc: ssh into sde guest vm
    dir: '/opt/sde/vagrant/sde'
    cmds:
      - vagrant ssh

  sde:vagrant:status:
    desc: print sde vagrant status
    dir: '/opt/sde/vagrant/sde'
    cmds:
      - vagrant status
  
  sde:vagrant:up:
    desc: bring up sde guest vm
    dir: '/opt/sde/vagrant/sde'
    deps: [sde:vagrant:init]
    cmds:
      - SDE_IPADDR="{{.SDE_IPADDR}}" vagrant up 

  
